# Certificate
---
apiVersion: v1
data:
  tls.crt: {{ .Values.secrets.BITS_TLS_CRT | b64enc }}
  tls.key: {{ .Values.secrets.BITS_TLS_KEY | b64enc }}
kind: Secret
metadata:
  name: private-registry-cert
type: Opaque
